=== sh0gg/programacion/marcas/XML/DTD/tarea5/UD3_T5_tarefa5b_davidBesada.dtd
<!ELEMENT reservas (reserva*)>
<!ATTLIST reservas ano CDATA #REQUIRED>
<!ELEMENT reserva (data, evento?, (clienteEmpresa | clientePersoal))>
<!ATTLIST reserva
  local (Polideportivo | Local_Social) #REQUIRED
  bonificacion CDATA #IMPLIED>
<!ELEMENT data EMPTY>
<!ATTLIST data
  mes CDATA #REQUIRED
  dia CDATA #REQUIRED
  horario (mañá | tarde | día) "tarde">
<!ELEMENT evento (#PCDATA)>
<!ELEMENT clienteEmpresa (#PCDATA)>
<!ELEMENT clientePersoal (#PCDATA)>

=== sh0gg/programacion/marcas/XML/DTD/tarea5/UD3_T5_tarefa5b_davidBesada.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE reservas SYSTEM "UD3_T5_tarefa5b_davidBesada.dtd">

<reservas ano="2012">
  <reserva local="Local Social" bonificacion="10%">
    <data mes="febreiro" dia="14" horario="dia" />
    <evento>Quedada moteros</evento>
    <clienteEmpresa>Los amantes del asfalto</clienteEmpresa>
  </reserva>
    <reserva local="Polideportivo">
    <data mes="marzo" dia="5"/>
    <evento>Campeonato mundial de petanca extrema</evento>
    <clientePersoal>Don Gregorio "El imbatible"</clientePersoal>
  </reserva>
</reservas>
