<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE mensaxe [
    <!ELEMENT mensaxe (de, para+, asunto, corpo?, adxunto*)>
    <!ATTLIST mensaxe prioridade (baixa | normal | urxente) "normal">
    <!ATTLIST mensaxe gardarBandexa CDATA "Enviados">
    <!ELEMENT de (#PCDATA)>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT corpo (#PCDATA)>
    <!ELEMENT adxunto (#PCDATA)>
]>

<mensaxe prioridade="urxente" gardarBandexa="Enviados">
   <de>maria@gmail.com</de>
   <para>ignacio@gmail.com</para>
   <para>pedro@edu.xunta.es</para>
   <asunto>Env√≠oche os arquivos</asunto>
   <adxunto>D:\fotos\dePesca.jpg</adxunto>
   <adxunto>D:\docs\carta.odt</adxunto>
   <adxunto>D:\fotos\naCea.jpg</adxunto>
</mensaxe>
