=== sh0gg/programacion/marcas/XML/DTD/tarea6/UD3_T6_tarefa6B_davidBesada.dtd
<!DOCTYPE Hardware [
    <!ELEMENT Hardware (Fabricante*, Espazo*, Maquina*)>

    <!ELEMENT Fabricante (nome, Web, correo)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT Web (#PCDATA)>
    <!ELEMENT correo (#PCDATA)>
    <!ATTLIST Fabricante id ID #REQUIRED>

    <!ELEMENT Espazo (nome, tipo, ubicación, ordenador*)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT ubicación (#PCDATA)>
    <!ELEMENT ordenador EMPTY>
    <!ATTLIST ordenador ref IDREF #REQUIRED>

    <!ELEMENT Maquina (Info, Config, Notas?)>
    <!ATTLIST Maquina 
        Nome ID #REQUIRED
        fabricante IDREF #REQUIRED>

    <!ELEMENT Info (Tipo, Procesador?, Memoria?, Disco*, (Lectora | Gravadora)?)>
    <!ELEMENT Tipo (#PCDATA)>
    <!ELEMENT Procesador (#PCDATA)>
    <!ELEMENT Memoria (#PCDATA)>
    <!ELEMENT Disco EMPTY>
    <!ELEMENT Lectora (#PCDATA)>
    <!ELEMENT Gravadora (#PCDATA)>

    <!ELEMENT Config (Role*, OS?, IP*, Gateway?)>
    <!ELEMENT Role (#PCDATA)>
    <!ELEMENT OS (#PCDATA)>
    <!ELEMENT IP (#PCDATA)>
    <!ELEMENT Gateway (#PCDATA)>
    
    <!ELEMENT Notas (#PCDATA)>
]>

=== sh0gg/programacion/marcas/XML/DTD/tarea6/UD3_T6_tarefa6B_davidBesada.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hardware SYSTEM "UD3_T6_tarefa6B_davidBesada.dtd">
<Hardware>
    <Fabricante id="FAB1">
        <nome>Lenovo</nome>
        <Web>www.lenovo.com</Web>
        <correo>contact@lenovo.com</correo>
    </Fabricante>

    <Espazo>
        <nome>Aula Informática</nome>
        <tipo>aula</tipo>
        <ubicación>Edificio A, Planta 1</ubicación>
        <ordenador ref="PC1"/>
        <ordenador ref="PC2"/>
    </Espazo>

    <Maquina Nome="PC1" fabricante="FAB1">
        <Info>
            <Tipo>Portátil</Tipo>
            <Procesador>Intel Core i5</Procesador>
            <Memoria>8GB</Memoria>
            <Disco Capacidade="512GB" Tecnoloxía="SSD"/>
        </Info>
        <Config>
            <OS>Windows 10</OS>
            <IP>192.168.1.10</IP>
        </Config>
    </Maquina>

    <Maquina Nome="PC2" fabricante="FAB1">
        <Info>
            <Tipo>Sobremesa</Tipo>
            <Procesador>AMD Ryzen 7</Procesador>
            <Memoria>16GB</Memoria>
            <Disco Capacidade="1TB" Tecnoloxía="SATA"/>
        </Info>
        <Config>
            <OS>Linux</OS>
            <IP>192.168.1.11</IP>
        </Config>
    </Maquina>
</Hardware>
